---
title: "Research Paper"
author: "Bao Dinh, Iris Sun, Saki Uwagawa, Landon Young"
date: "March 7, 2017"
output:
  html_document: default
  pdf_document: default
---


## Marijuana Use In United States in 2014

### _ABSTRACT_
This project serves the purpose to _explore the relationships_ between **marijuana use** and various factors such as **demographics**, **education and income levels**, and **mental health state**. As the legalization of both medicinal and recreational marijuana becomes more prominent throughout our country, our hope is to provide both policy makers and the general public more information about the trends in marijuana use. Among our findings between age groups, education level, sex, and marijuana usage, we also found that in general, _those who have used marijuana_ tend to be associated with _higher risk to answering questions_ that have some **concerns in regards to mental health**. While other studies may present their findings in a biased manner (e.g. pro or anti marijuana stance), this research study aims to provide information in an **objective** manner to allow readers to make their own decisions by using non-biased data. 

### _INTRODUCTION_
The purpose of our study is to **explore the impact of marijuana use** in the US population and bring awareness to the topic, especially as more states are moving to _legalize marijuana_. Specifically, we will be exploring how marijuana use breakdown across different demographics (age, sex, and race), education and income levels, and mental health state.
Because we are simply exploring the possible correlation and patterns, we attempt to take a relatively **neutral and unbiased** approach when displaying and analyzing our data. We agreed on an interactive Shiny application as the deliverable for this study to give the users the freedom to explore the we analyzed information on their own, allowing them to come up with their _own opinions_ regarding the topic with the _guidance of our tool_. We hope this tool helps answer relevant questions and provide insight regarding marijuana use to policy makers and potential users.

### _RELATED WORKS_
With the large interest surrounding the effects of marijuana usage, there are many research studies and scholarly articles outlining the impacts of this drug. Through the study _Adverse health effects of non-medical cannabis use_, their findings outlined “effects [including] a dependence syndrome, increased risk of motor vehicle crashes, impaired respiratory function, cardiovascular disease, and adverse effects of regular use on adolescent psychosocial development and mental health” from cannabis usage [(source)](http://mobile.legaliser.nu/sites/default/files/files/Adverse%20health%20effects%20of%20non-medical%20cannabis%20use.pdf). All of their findings heavily defined the negative characteristics associated with marijuana and thus was an article that ultimately took an opposing position to the drug. 

Another study, _Adverse Health Effects of Marijuana Use_ outline the effects of marijuana on brain development, school performance, its role as a gateway drug, and risk of addiction. While this study reports on the negative aspects of marijuana, the report still touches on the “limitations of the evidence and gaps in knowledge” which is helpful and informative when presenting information that is very relevant and influential for how policy makers and other higher officials will perceive marijuana [(source)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4827335/). This allows for readers to better understand and be aware of the restrictions that come along with this data and better judge the facts for how they came about. 

### _METHODS_
We decided to use the National Survey on Drug Use and Health, 2014 (ICPSR 36361) as our dataset. The _survey package_ in R was used to analyze the dataset. The strata and weight information was provided by ICPSR, VESTR and ANALWT_C respectively. After finding a usable dataset, our next step was to establish three exploratory questions to base our study on. The questions are as follows:
_How does marijuana use break down across **age, sex, and race**?
What is the spread of marijuana users across varying **education and income levels**?
What correlations can be found between the self-reported **mental health** of marijuana users?
In order to answer the above questions, we decided to create four interactive visuals, splitting the first questions into two different visuals where one includes both marijuana users and non users and the second looks at marijuana users specifically. When selecting the specific columns to analyze, we did our best not to include questions which may have been legitimately skipped in order to avoid disrupting the flow of the questionnaire. For example, if a participant answered they did not exercise, they would not be asked “How many times a week do you exercise?” This was to represent as much of the dataset as possible, so that we were not favoring any specific demographic of participants. 

__Demographic Information:__
For the first demographic graph, we looked at NEWRACE2, IRSEX, CATAG6, and MJEVER which represents race, sex, age group and whether the respondent has ever used marijuana. We look at both marijuana users and nonusers for this section to get an overview of the demographics of people who have decided to use marijuana as well as people who have decided not to use marijuana. For this graph, we look at frequency or count of the people who fall under the category.
For the second demographic graph, we look specifically at the demographic breakdown of marijuana users. For this section, we looked at MJAGE, MJREC, and MJDAY as well as the demographic columns used in the first graph. MJAGE represents the age at which a person first use marijuana. MJREC represents how long it has been since the respondent last used marijuana. Finally, MJDAY30A represents how many days the respondent used marijuana in the last 30 days. 

__Education and Income Level:__
For education and income levels, we looked at MJEVER, as used in the previous graphs, EDUCCAT2 which presents the education level received by the respondent, IRPINC3 which represents the respondent’s total income, and finally IRFAMIN3 which represents the respondent’s family’s total income. One of the category labels for EDUCCAT2 is “12 to 17 year olds” which includes students who are still in high school but have not yet completed high school. This is different from “Less than high school” which includes adults who did not attend or complete high school. 
We decided to include both individual and family income in our graph because we were unsure of the difference and impact it would have on the visualization. Also, this way children or students who do not have income of their own but do have access to money can still be represented in the data. 

__Mental Health:__
We looked at many different columns to explore correlation between mental health and usages of marijuana. The list of columns are as follows: MJEVER, DSTNRV30, DSTHOP30, DSTRST30, ADDPREV, SUITHNK, SUIPLAN, SUICTRY. Since marijuana is commonly used to sooth nerves and pain and often used by people struggling with depression, we decided the avenue of mental health was critical in understanding marijuana users.
DSTNRV30, DSTHOP30, and DSTRST30 ask whether the respondent has felt nervous, hopeless or restless/fidgety in the past 30 days. ADDPREV asks whether the respondent has ever felt sad, empty, or depressed for several days or longer. SUITHNK, SUIPLAN, and SUICTRY ask whether the respondent has thought of, planned, or attempted suicide in the past. All of these questions were looked at against whether the respondent has ever used marijuana.

### _RESULTS_

__Demographic Information:__
When measuring the number of people who had ever smoked marijuana, we found interesting proportions among the different demographic groups. In measuring by age, we saw that the leading group who answered yes was ages 26-34 year olds (55.69%). Following were groups 50-64 year olds (53.79%), 18-25 year olds (53.23%), 35-49 year olds (50.15%), 65+ (21.99%), and 12-17 (16.44%) year olds in that order. A notable observation from this data set is the large increase in people who have smoked marijuana after the 12-17 year old age group. 
In measuring by sex, more men (49.55%) than women (39.30%) had smoked marijuana. This may not seem as a surprise to many as men are known to partake and be exposed to riskier behavior than women. However, the difference in percentages is quite notable as 10% is a large contrast when populations are being estimated in the hundreds of millions.

Lastly, in measuring by race, the leading group who answered yes was Native Americans/Alaskan Natives (55.60%). Following were groups More than one race (53.99%), Native Hawaiians/Other Pacific Islanders (49.78%), White (49.38%), Black/African American (42.45%), and Asian (17.74%). Although Native Americans/Alaskan Natives, Native Hawaiians/Other Pacific Islanders, and More than one race, ranked top three, it is important to keep in mind that the number of people surveyed from those groups was far less than any of the other ethnic groups. This may affect the accuracy of these results because certain groups may be underrepresented. 

Across marijuana users only, we found that the most common age people first used marijuana was 16-years-old. This was consistent across almost all races (18 was highest for Asians and Pacific Islanders), across both sexes, and across almost all age groups, only excluding 12- to 17-year-olds and respondents aged 65 or higher. Surprisingly, for 65-year-olds and up (65+), 16 did not even come in the top ten for age first used. The top six ages that 65+ first used marijuana were 20-years-old (68 respondents), 21y.o. (64r.), 25y.o. (63r.), 30y.o. (63r.), 18y.o. (57r.), and 35y.o. (57r.). 
We also found that age groups with the most recent users were 18- to 25-year-olds and 26- to 35-year-olds. The 18-25 group made up 30.82% of users that had used marijuana in the last 30 days, and 33.13% of users that had used marijuana in the last 12 months. The 26-35 group made up 21.32% of users who used in the last 30 days, and 22.52% of users who used in the past 12 months. 
When asked how many days they had used marijuana in the last 30 days, the majority of users reported that they had used marijuana every day. The only exceptions to this were the 12-17 and 65+ age groups, as well as Asians and Pacific Islanders. The number of Asians that reported only using marijuana 1 day of the last 30 was 13% higher than those reporting 30, while the number of Whites, for example, who reported using 30 of the last 30 days was 32% higher than those reporting only 1 day.

__Education and Income Level:__
When looking at education received and whether the respondent has ever used marijuana, of the people that answered yes, 3.5% were 12 to 17 years old, 27.1% were high school graduates, 30.3% were college graduates, 29.1% attended some college, and 9.9% did not graduate from high school. Of the respondents who answered that they have never used marijuana, 14.1% were 12 to 17 years old, 25.4% were high school graduates, 25.7% were college graduates, 21.2% attended some college and 13.7% did not graduate from high school.
In regards to individual income, both groups had a bigger proportion respondents who answered they had less than $10,000 annual income. We observed a decrease in proportion for both groups and the lowest percentage was observed at $40,000 - $49,999 annual income for both categories. The percentage of nonusers was higher for the first three income levels, but flips from the $30,000 - $39,999 income level. The difference in the two groups increase as it moves up income level from this point on.
For family income levels, we see a very different trend from the individual income graph. Percentages for both groups increase as you move up the income level on the x-axis. All throughout, the percentages of the two groups are relatively close except for the last income level, $75,000 or more, where there is a higher percentage of users by 4.5%.

__Mental Health:__
In regards to mental health questions, when asked how often the respondents felt restless within the last 30 days, 47.1% said “None of the time”, 29.2% said “A little of the time”, 17.1% said “Some of the time”, 4.4% said “Most of the time” and 2.1% said “All of the time”. As we apply weights to these percentages, we see that this would correspond to represent around 240 million people in the US. This would correlate to around 121 million people answering “None of the time”, 70.2 million answering “A little of the time”, 35 million answering “Some of the time”, 8 million answering “Most of the time”, and 4 million answering “All of the time”. That’s 12 million Americans living life feeling some sort of uneasiness. Similar results were found for the nervous and hopeless questions.

As we break down the survey data by those who have used marijuana and those who have not, we see that those who are users often answered higher in the “All of the time”, “Most of the time” and “Some of the time”. When we look specifically at “how often did you feel restless” we see that for non-users, 1.6% of the respondents answered “All of the time” compared to that of 2.5% for users. This trend continues for “Most of the time” and “Some of the time”, where users who have used marijuana resulted in higher total. Although there may be many confounding variables that may have caused users to often feel more restless, nervous and hopeless, these results do suggest that there potentially could be an association and that further study should be done in order to eliminate confounding variables and conclude whether marijuana had any effect on mental well being of an individual.

As we look more into the potential relationship between mental health and marijuana, we will assess the data collected from the suicidal behavior questions. When asked whether the respondent “seriously thought about trying to kill yourself” within the past 12 months, around 70.1% of the respondents that answered “Yes” were users compared to that of around 29.9% which were non-users. Of those that answered “No”, around half were users and half were non-users. This result shows that for those who have thought about committing suicide in the past 12 months, the majority of them have used marijuana. When we apply the weights to the percentages, we see that around 9.5 million people in the past 12 months have thought about committing suicide. Of those 9.5 million people, 6.5 million have used marijuana in the past. As we view the calculations for attributable risk due to the exposure of marijuana, we see that 29% of the incidence in suicidal thinking in those who have used marijuana is attributable to marijuana. Similar results were found for questions about “planning to kill yourself” and “trying to kill yourself”, in that those who have used marijuana tend to answer “Yes” to these questions. 

### _DISCUSSION_

__Demographic Information:__
A surprising measurements was the large decrease in age group 65+ for people who answered yes to having ever smoked marijuana. We figured the older the age group (especially over 18), the more exposure they would have had to the opportunity of smoking weed, thus the low percentage for the oldest age group was surprising. Combined with the remaining findings of marijuana usage between the sexes and ethnic groups, policy makers may find this information useful in making decisions for what their policies may be and who their policies extend to. 

By knowing that the most common age people had first used marijuana is 16, and that the next highest ages were primarily between ages 12 and 21, we can implement policies and programs to inform middle school, high school, and college students of the effects of marijuana. This way the group that is most likely to try marijuana for the first time can have more comprehensive information about the drug when making a decision to use it or not.
Lastly, by understanding the age group with the most current users is between 18 and 34 can help us understand the user base better. As marijuana becomes more legalized, there may be more of a focus on this audience considering they are the primary users. 

__Education and Income Level:__
For education levels, we saw a greater percentage of marijuana users for people who completed high school and above when compared to the proportion of nonusers. The opposite trend was true for respondents who are still 12 to 17 years old or people who did not complete high school. This seems to reflect the idea that many people try marijuana in college.
When looking at the individual income level, we see that the proportion of users is greater than that of nonusers from $30,000 annual income group. This is interesting because it means that the odds of someone in the high individual income level having tried marijuana is greater. Some possible explanations for this is that many people who were hippies and used marijuana at the time are now at a point in their professional life where they are making much more. However, without looking at the age breakdown, it would be hard to make this inference. 
For family income levels, as mentioned above, we see that generally the proportions for nonusers and users are relatively equal for the most part, except for the group that answered their annual family income was $75,000 or greater. This difference in the two groups for high income category is consistent with the individual income level. However, the rest of the categories vary significantly in terms of trend when compared to the individual income. This makes sense since many students, who most likely do not have an income, make up a great proportion of the first category. However, in the second graph, they are spread out throughout the varying income levels. 

__Mental Health:__
It is important to note that although our results indicate that having used marijuana at least once is typically associated with having poor mental health, we have to understand the limitation of our data set. Due to the simplicity of the questions asked within the survey, we were only able to measure whether the respondent had ever used marijuana. This is important to note because by relating it to some mental health questions, we aren’t able to see the true impact that marijuana has on mental health. For instance, perhaps the respondent stopped using marijuana but uses other substances and as a result, their mental health is diminishing. A better way to assess relationship would be to look that those who are currently using marijuana, and then assess the state of their mental health. 

### _FUTURE WORK_

Although analysis of the 2014 National Survey on Drug Use and Health has provided us with many insightful correlations between mental health, demographics, and marijuana use, there are still many questions about causal effects. For example, according to our analysis, it appears that marijuana users tend to feel generally more nervous, restless, and hopeless than those who do not use marijuana. However, we do not have enough information or evidence to suggest whether these feelings are caused by marijuana, or if people with these feelings tend to use marijuana while those without these feelings tend not to. Future studies could be done to try and pin this causation down, allowing us to understand marijuana use much better. 

Also, due to the fact that we pulled our information from a survey that asks questions about several different kinds of drugs, we were not able to look at a very large number of marijuana users. After filtering the data by people who had used marijuana even once (not necessarily regular marijuana users), we were left with only 55,271 respondents. This is only 0.017% of the 318.9 million person population. In order to find out more about causation, gathering as many regular users as possible would likely be more accurate and helpful than extrapolating the effects on this smaller sample of users to the rest of the population.






